jobs:
  - name: ecs-man1
    type: manifest
    steps:
      - IN: ecs-img1
      - IN: ecs-tg1

  - name: ecs-deploy1up
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade
