jobs:
  
#MANIFESTS
      
  - name: real-man1
    type: manifest
    steps:
      - IN: real-img1
      - IN: real-dopts1
      - IN: real-scale1
      - IN: real-tg1
      
  - name: real-ecsdeploy
    type: deploy
    steps:
      - IN: real-man1
      - IN: real-ecscluster
      
  - name: real-ecsdeploy2
    type: deploy
    steps:
      - IN: real-release1
      - IN: real-ecscluster
      
# REALESE

  - name: real-release1
    type: release
    steps:
      - IN: real-version2
      - IN: real-ecsdeploy
      - TASK: managed
        bump: beta        
        
  - name: RL-rele
    type: release
    steps:
      - IN: real-version4
      - IN: real-img2
      - IN: real-dopts1
      - IN: real-params1
      - IN: real-scale1
      - IN: real-ecscluster
    #  - IN: real-ecsdeploy4
      - TASK: managed
        bump: alpha
        
  - name: real-release5
    type: release
    steps:
      - IN: real-version1
     # - IN: real-ecsdeploy6release
      - TASK: managed
        bump: major
        
  - name: real-release6
    type: release
    steps:
      - IN: real-version6
    #  - IN: real-man6
      - TASK: managed
        bump: rc
        
  - name: real-inrunsh
    type: runSh
    steps:
      - IN: real-sample-script-rs
       # versionName: testsha
      - IN: real-tg2
      - TASK:
        - script: ls
        - script: ./IN/sample-script-rs/gitRepo/echo.sh
