jobs:
  
#MANIFESTS
      
  - name: uitest-man1
    type: manifest
    steps:
      - IN: uitest-img1
      - IN: uitest-tg1
      
  - name: uitest-man2
    type: manifest
    steps:
      - IN: uitest-img2
      - IN: uitest-tg2
      
  - name: uitest-man3mftomf
    type: manifest
    steps:
      - IN: uitest-man2
        switch: off
      - IN: uitest-man5
      
  - name: rc-man1
    type: manifest
    steps:
      - IN: uitest-man1
      - IN: uitest-man3mftomf
      
  - name: uitest-man5
    type: manifest
    steps:
      - IN: uitest-img3
      - IN: uitest-tg3
      
  - name: uitest-man6
    type: manifest
    steps:
      - IN: uitest-man1
        switch: off
      - IN: uitest-man2
        switch: on
  
  - name: uitest-man7
    type: manifest
    steps:
      - IN: uitest-img1
      - IN: uitest-dopts1
      - IN: uitest-tg1

  - name: uitest-ddcdeploy
    type: deploy
    steps:
      - IN: uitest-man1
      - IN: uitest-dopts1
      - IN: uitest-ddccluster
