jobs:
  - name: lb-mani1
    type: manifest
    steps:
      - IN: lb-imglb
      - IN: lb-dopt1
      - IN: lb-tg1  
      
  - name: lb-ecsDeploy1
    type: deploy
    steps:
      - IN: lb-mani1
      - IN: lb-ecscluster
      - IN: lb-loadb2
        applyTo:
          - manifest: lb-mani1 # it can only apply to one manifest
            image: lb-imglb # it can only apply to one image in the manifest
      - TASK: managed
        deployMethod: upgrade
