jobs:

#MANIFESTS
      
  - name: easyt-man1
    type: manifest
    steps:
      - IN: easyt-img1
      - IN: easyt-tg1
      
  - name: easyt-man2
    type: manifest
    steps:
      - IN: easyt-img1
      - IN: easyt-tg1
