triggers:
   - name: bbs2allpl-tg1
     type: trigger
     version:
       counter: 0
       
   - name: bbs2allpl-tg2
     type: trigger
     version:
       counter: 0
       
   - name: bbs2allpl-tg3
     type: trigger
     version:
       counter: 0
