triggers:
   - name: dep-tg1
     type: trigger
     version:
       counter: 3
       
   - name: dep-tg2
     type: trigger
     version:
       counter: 3
       
   - name: dep-tg3
     type: trigger
     version:
       counter: 0
       
   - name: dep-tg4
     type: trigger
     version:
       counter: 0
       
   - name: dep-tg5
     type: trigger
     version:
       counter: 2
       
   - name: dep-tg6
     type: trigger
     version:
       counter: 0
