jobs:
#MANIFESTS
      
  - name: ecs-man1
    type: manifest
    steps:
      - IN: ecs-img1
      - IN: ecs-img2
      - IN: ecs-dopts1
    #  - IN: ecs-params1
      - IN: ecs-tg1
      
  - name: ecs-man2
    type: manifest
    steps:
      - IN: ecs-img3
      - IN: ecs-dopts1
      
 # - name: ecsman2-invalidimg
  #  type: manifest
   # steps:
    #  - IN: ecsimg2-tagdoesntexist
     # - IN: ecs-tg2
      
 # - name: ecsman3-invalid
  #  type: manifest
   # steps:
    #  - IN: ecs-img2
     #   versionNumber: 369
     # - IN: ecs-tg3

# DEPLOYMENTS 

  - name: BG-deploy1
    type: deploy
    steps:
      - IN: ecs-man2
      - IN: ecs-cluster      
        
  - name: RP-deploy1
    type: deploy
    steps:
      - IN: ecs-man2
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: replace
      
 # - name: ecs-deploy2bginvalidclu
  #  type: deploy
   # steps:
    #  - IN: ecs-man1
     # - IN: ecsclu2-invalidclu
      
 # - name: ecs-deploy3upinvalidimg
  #  type: deploy
   # steps:
    #  - IN: ecsman2-invalidimg
     # - IN: ecs-cluster
      #- TASK: managed
       # deployMethod: upgrade

 # - name: ecs-deploy4bgmani
  #  type: deploy
   # steps:
    #  - IN: ecsman3-invalid
     # - IN: ecs-cluster
      
 # - name: ecs-deploy5upinvaliddopts
  #  type: deploy
    #steps:
   #   - IN: ecs-man1
     # - IN: ecs-dopts2invalid
      #- IN: ecs-cluster
      
