jobs:

#RELEASE

  - name: dep-release
    type: release
    steps:
      - IN: flsv-version2
      #  versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: flsv-man1
      - IN: flsv-tg6
    flags:
      - flsv-release
      
#MANIFESTS
      
  - name: dep-man1up
    type: manifest
    steps:
      - IN: dep-img1
      - IN: dep-tg1
    on_start:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
    on_success:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
      
  - name: dep-man2bg
    type: manifest
    steps:
      - IN: dep-img2
      - IN: dep-tg2
    # on_start:
    #   - NOTIFY: dep-email
    #   - NOTIFY: dep-slack
    # on_success:
    #   - NOTIFY: dep-email
    #   - NOTIFY: dep-slack
  
  - name: dep-man3
    type: manifest
    steps:
      - IN: dep-img3
      - IN: dep-tg3
      
  - name: dep-man4toman3
    type: manifest
    steps:
      - IN: dep-man3

# DEPLOYMENTS 

  - name: dep-ecsdeployup
    type: deploy
    steps:
      - IN: dep-man1up
      - IN: dep-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: dep-ecsdeploybg
    type: deploy
    steps:
      - IN: dep-man2bg
      - IN: dep-ecscluster
    on_start:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
    on_success:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
      
  - name: dep-ecsdepupmftomf
    type: deploy
    steps:
      - IN: dep-man4toman3
      - IN: dep-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
    on_success:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
        
  - name: dep-ecsdeployupmultiimg
    type: deploy
    steps:
      - IN: dep-man1up
      - IN: dep-man3
      - IN: dep-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
    on_success:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
      
  - name: dep-tpdeployup
    type: deploy
    steps:
      - IN: dep-man1up
      # - IN: flsv-params5
      #   applyTo:
      #     flsv-man8
      - IN: dep-tripubcluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: dep-tpdeploybg
    type: deploy
    steps:
      - IN: dep-man2bg
        #switch: off
      - IN: dep-tripubcluster
    on_start:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
    on_success:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
      
  - name: dep-gkedeployup
    type: deploy
    steps:
      - IN: dep-man1up
      - IN: dep-gkecluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: dep-gkedeploybg
    type: deploy
    steps:
      - IN: dep-man2bg
      - IN: dep-gkecluster
    on_start:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
    on_success:
      - NOTIFY: dep-email
      - NOTIFY: dep-slack
      
  - name: dep-dcldeploy
    type: deploy
    steps:
      - IN: dep-man1up
      - IN: dep-params1
      - IN: dep-dclcluster
        
  - name: dep-ddcdeploy
    type: deploy
    steps:
      - IN: dep-man1up
      - IN: dep-ddccluster
      
#runSh
  # - name: flsv-inrunsh
  #   type: runSh
  #   steps:
  #     - IN: flsv-sample-script1
  #       #versionName: "149dc247602ba40192703b5fe0a1bfae01bd8490"
  #     - IN: flsv-tg6
  #     - IN: flsv-img1
  #     - IN: flsv-man1
  #     - TASK:
  #       - script: ls
  #       - script: ./IN/flsv-sample-script1/gitRepo/echo.sh
  #       - script: sudo apt-get install tree
  #       - script: tree -F IN
  #       - script: cat IN/flsv-man1/integration.json
       # - script: export versionName=$(cat ./IN/fl-img1/version.json | jq -r '.version.versionName')
        
  # - name: flsv-inrunsh3
  #   type: runSh
  #   steps:
  #     - IN: flsv-sample-script1
  #     - IN: flsv-man1
  #   #  - IN: flsv-email
  #     - IN: flsv-img1
  #     - IN: flsv-dockerint
  #     - IN: flsv-tg6
  #     - TASK:
  #       - script: ls
  #       - script: ./IN/flsv-sample-script1/gitRepo/echo.sh
  #     # - script: sl
  #       - script: sudo apt-get install tree
  #       - script: tree -F IN
  #       - script: cat IN/flsv-man1/integration.json
  #   on_failure:
  #     - script: echo 'testing1 failure'
  #     - script: echo 'failure runSh'
  #     - NOTIFY: flsv-slack
  #     - NOTIFY: flsv-email
      
#  - name: flsv-outrunsh
   # type: runSh
  #  steps:
   #   - TASK:
      #  - script: "mkdir -p /build/state/" # creating directory 
       # - script: "touch /build/state/flsv-img1.env" # touch will create new empty file with timestamp
        #- script: "echo 'Hello'"
       # - script: "echo 'versionName=latest' >>  /build/state/rs-img1.env" # this will be adding in the file mongo-image.env
        #- script: "echo 'anotherProperty=foo' >>  /build/state/rs-img1.env" # next line will be this in the file mongo-image.env
      #  - script: ls # fail case to post version for OUT image when all above commands are commented. that means it is nt to able to create an env folder for that image so it cant post version
     # - OUT: flsv-img1
    #  - IN: flsv-tg11
    #  - IN: "2img-rs"
     # - IN: "redis-rs"
     # - OUT: "env-rs"
      
  #- name: flsv-runCI2
   # type: runCI
    #steps:
     # - IN: flsv-sample-nod-notifiction
      #- TASK: managed
      #- OUT: flsv-img9
      #- IN: flsv-tg3
        
#rSync
  # - name: flsv-rsyncjob
  #   type: rSync
  #   steps:
  #     - IN: "flsrsv_sample-fleming_sr-rsync"
  #     - IN: fl-tg6
    

