jobs:
#MANIFESTS
  - name: dcl-man3
    type: manifest
    steps:
      - IN: dcl-img3
 #     - IN: dcl-dopts1
      - IN: dcl-tg1
        
  - name: dcl-deploy1
    type: deploy
    steps:
      - IN: dcl-man3   
      - IN: dcl-cluster
