jobs:

#RELEASE

  - name: bbs2allpl-release
    type: release
    steps:
      - IN: bbs2allpl-version
        #versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: bbs2allpl-tg3
    flags:
      - release_allplbbs2
    on_start:
      - NOTIFY: bbs2allpl-email
    on_success:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
      
#MANIFESTS
      
  - name: bbs2allpl-manifest1
    type: manifest
    steps:
      - IN: bbs2allpl-image1
       # versionNumber: 100
      - IN: bbs2allpl-tg1
    on_start:
      - NOTIFY: bbs2allpl-email
    on_success:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
      
#DEPLOYMENTS:
  - name: bbs2allpl-tpdeploybg
    type: deploy
    steps:
      - IN: bbs2allpl-manifest1
       # switch: off
      - IN: bbs2allpl-dopts
      - IN: bbs2allpl-tripubcluster
    on_start:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
    on_success:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
    on_failure:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
      
  - name: bbs2allpl-ddcdeploy
    type: deploy
    steps:
      - IN: bbs2allpl-manifest1
      - IN: bbs2allpl-dopts
      - IN: bbs2allpl-ddccluster
      
  - name: bbs2allpl-dcldeploy
    type: deploy
    steps:
      - IN: bbs2allpl-manifest1
      - IN: bbs2allpl-dopts
      - IN: bbs2allpl-dclcluster
    on_success:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
    on_failure:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
      
  - name: bbs2allpl-ecsdeployup1
    type: deploy
    steps:
      - IN: bbs2allpl-manifest1
      #  switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: bbs2allpl-dopts
      - IN: bbs2allpl-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
    on_failure:
      - NOTIFY: bbs2allpl-email
      - NOTIFY: bbs2allpl-slack
      
  - name: bbs2inrunsh
    type: runSh
    steps:
      - IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    on_start:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  
