jobs:
  - name: lb-mani1
    type: manifest
    steps:
      - IN: lb-imglb
      - IN: lb-dopt1
      - IN: lb-tg1
      
  - name: lb-mani2
    type: manifest
    steps:
      - IN: lb-imglb
      - IN: lb-dopt2
     
      
  - name: lb-mani3
    type: manifest
    steps:
      - IN: lb-imglb
      - IN: lb-dopt3
     

  - name: lb-ecsDeploy1
    type: deploy
    steps:
      - IN: lb-mani1
      - IN: lb-ecscluster
      - IN: lb-loadb2
        applyTo:
          - manifest: lb-mani1 # it can only apply to one manifest
            image: lb-imglb # it can only apply to one image in the manifest
            port: 80
      - TASK: managed
        deployMethod: upgrade
        
  - name: lb-ecsDeploy2rp
    type: deploy
    steps:
      - IN: lb-mani2
      - IN: lb-ecscluster
      - IN: lb-loadb2
        applyTo:
          - manifest: lb-mani2 # it can only apply to one manifest
            image: lb-imglb # it can only apply to one image in the manifest
            port: "8082:80"
      - TASK: managed
        deployMethod: replace

  - name: lb-ecsDeploy3bg
    type: deploy
    steps:
      - IN: lb-mani3
      - IN: lb-ecscluster
      - IN: lb-loadb2
        applyTo:
          - manifest: lb-mani3 # it can only apply to one manifest
            image: lb-imglb # it can only apply to one image in the manifest
            port: "9090:9090"
