jobs:
#MANIFESTS
      
  - name: ecs-man1
    type: manifest
    steps:
      - IN: ecs-img1
      - IN: ecs-tg1
      
 

# DEPLOYMENTS 

  - name: ecs-d9
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecs-cluster
      - TASK: managed
       # deployMethod: upgrade
      
  - name: test-runsh
    type: runSh
    steps:
      #- IN: allpl-sample-script
      - IN: test-time
     # - IN: allpl-tg2
      #- IN: test-time-1
      - TASK:
        - script: ls
       # - script: ./IN/allpl-sample-script/gitRepo/echo.sh
      
