jobs:
#MANIFESTS
      
  - name: ecs-man1
    type: manifest
    steps:
      - IN: ecs-img1
      - IN: ecs-tg1
      
 

# DEPLOYMENTS 

  - name: ecs-d3
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecs-cluster
      - TASK: managed
       # deployMethod: upgrade
      
 
      
